# Generated by Django 5.2.5 on 2025-08-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_courseunit_program_studentprofile_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programcourse',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Semester One'), (2, 'Semester Two')], max_length=50),
        ),
    ]
